"""Compatibility exports for relocated typed application events."""

from yoyopod.core.events import (
    CallEndedEvent,
    CallStateChangedEvent,
    IncomingCallEvent,
    MusicAvailabilityChangedEvent,
    NetworkGpsFixEvent,
    NetworkGpsNoFixEvent,
    NetworkModemReadyEvent,
    NetworkPppDownEvent,
    NetworkPppUpEvent,
    NetworkRegisteredEvent,
    NetworkSignalUpdateEvent,
    PlaybackStateChangedEvent,
    RecoveryAttemptCompletedEvent,
    RegistrationChangedEvent,
    ScreenChangedEvent,
    TrackChangedEvent,
    UserActivityEvent,
    VoIPAvailabilityChangedEvent,
)

__all__ = [
    "CallEndedEvent",
    "CallStateChangedEvent",
    "IncomingCallEvent",
    "MusicAvailabilityChangedEvent",
    "NetworkGpsFixEvent",
    "NetworkGpsNoFixEvent",
    "NetworkModemReadyEvent",
    "NetworkPppDownEvent",
    "NetworkPppUpEvent",
    "NetworkRegisteredEvent",
    "NetworkSignalUpdateEvent",
    "PlaybackStateChangedEvent",
    "RecoveryAttemptCompletedEvent",
    "RegistrationChangedEvent",
    "ScreenChangedEvent",
    "TrackChangedEvent",
    "UserActivityEvent",
    "VoIPAvailabilityChangedEvent",
]
